name: LaTeX Build and Upload

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # This step is replaced by pulling the image from GHCR
      - name: Pull Docker Image from GHCR
        run: docker pull ghcr.io/${{ github.repository_owner }}/latex-build:latest

      - name: Run Docker Container
        run: docker run -v $(pwd):/latex_content --name latex-container ghcr.io/${{ github.repository_owner }}/latex-build:latest /bin/sh -c "make pdf"

      - name: Copy PDF from Docker Container
        run: |
          docker cp latex-container:/latex_content/rendered.pdf esteban_martinena_cv.pdf
          docker cp latex-container:/latex_content/cover.png esteban_martinena_cv.png

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf-${{ github.ref_slug }}
          path: esteban_martinena_cv.*

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ contains(github.ref, 'tags') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "esteban_martinena_cv*"
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
          body: "Latest version of my CV."

      # TODO: Attach pdf to readme.md using sed and the latest release
      # -name: Attach pdf to readme.md
      #   run: |
        #     echo "![CV](
        #
        #     )"
        #     >> README.md

